### ISSUE TITLE
Check aria labels for bank assessment table header sort buttons

### ISSUE THREAD

**Issue by resource11** [CLIxIndia-Dev/OpenAssessmentsClient#184]
It's not clear to non sighted users what this button does, so we need aria labels for the arrows and most likely a better description for what 'name' and 'published' does

**Comment by resource11** [comment]
Here's an idea: considering both of these filter buttons have three sort states (sort ascending, sort descending, unsorted), how about some way of using a template string and perhaps a ternary statement to cycle through the three aria labels?

**Comment by cjshawMIT** [comment]
But do you put the "next" state as the `aria-label` (i.e. what the button will do), or the "current" state?

They both cycle from unsorted to ascending to descending. So when you load the page, it is unsorted. So what should the `aria-label` on the `Name` button be?

**Comment by cjshawMIT** [comment]
I'm also not clear that we would add `aria-label` to the arrows themselves, since you can't click on the arrows at all -- you click on the wrapping `button`. For example, you can't click on the "up" arrow and sort things in descending order -- the cycle is fixed.

**Comment by cjshawMIT** [comment]
Also, do we have the right arrow matching to the right action? Should the up arrow be highlighted when it is sorted in descending order?

**Comment by resource11** [comment]
Good point on how we choose to start the label cycling. Agreed that we don't need aria-label on arrow icons, those icons do need an aria-hidden attribute though.

I'll have to look again to see if the bold arrow vs sort order iscorrect as it stands

**Comment by cjshawMIT** [comment]
I'm wondering if we can just make the button `aria-label` more verbose. Currently it is like "Sort by Name, currently unsorted". Perhaps just add text like "Sort by name, current unsorted. Click to sort in ascending order"....
