### ISSUE TITLE
MW Sandbox gets stuck

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/OpenAssessmentsClient#197]
If you play with the words in MW sandbox, then click "check answer" without recording audio, the spinner spins forever and you can't do anything else. This only seems to happen if you play with the words -- the audio record button works fine if you do "check answer" without dragging the words.

![captura de pantalla 2018-02-16 a la s 11 18 10 am](https://user-images.githubusercontent.com/4930129/36317579-76b1cd0c-130b-11e8-9f25-337adf6ea277.png)

**Comment by resource11** [comment]
Ah, you replicated the same issue I was seeing a while back! The last time I ran into this issue, it was using an assessment authored with Onyx.
