### ISSUE TITLE
Move unlock previous and n of m selectors to the right

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/OpenAssessmentsClient#90]
Make them take up less space...so perhaps half the width instead of the whole width of the container.

Assumes #88 and #89 are done.

**Comment by cjshawMIT** [comment]
This has been done, though need to be styled.

**Comment by resource11** [comment]
Yes! This was the issue I was referencing earlier. Thanks for finding it again. :)
